eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://altkom-scah-service-registry:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: info,prometheus
spring:
  zipkin:
    base-url: http://altkom-scah-zipkin:9411/
