spring:
  cloud:
    gateway:
      routes:
        - id: owner-service
          uri: lb://owner-service
          predicates:
            - Path=/owner/**
        - id: dog-service
          uri: lb://dog-service
          predicates:
            - Path=/dog/**
        - id: reservation-service
          uri: lb://reservation-service
          predicates:
            - Path=/reservation/**
