spring:
  application:
    name: dog-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://altkom-scah-keycloak:8080/auth/realms/app-realm
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
  datasource:
    url: jdbc:postgresql://altkom-scah-dog-postgres:5432/dogdb
    username: postgres
    password: postgres
  flyway:
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
