spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://altkom-scah-keycloak:8080/auth/realms/app-realm
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
  datasource:
    url: jdbc:postgresql://altkom-scah-owner-postgres:5432/ownerdb
    username: postgres
    password: postgres
  flyway:
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
feign:
  client:
    config:
      default:
        connectTimeout: 2000
        readTimeout: 30000
      DOG-SERVICE:
        connectTimeout: 1000
        readTimeout: 5000
  circuitbreaker:
    enabled: true
    alphanumeric-ids:
      enabled: true
resilience4j:
  circuitbreaker:
    instances:
      DogClientgetOwnerDogsLong:
        sliding-window-size: 4
        failure-rate-threshold: 50
        wait-duration-in-open-state: 20s
        permitted-number-of-calls-in-half-open-state: 4
        automatic-transition-from-open-to-half-open-enabled: true
